swagger: '2.0'
info:
  version: 0.0.1
  title: DiskInformation
  description: >-
    A simple service to get Disk Information
    using swagger -2.0 specification and codegen
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Cloudmesh REST Service
  license:
    name: Apache
host: 'localhost:8080'
basePath: '/cloudmesh/disk'
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  '/TotalD':
    get:
      description: "Returns disk space information of the hosting server"
      produces: 
        - "application/json"
      responses:
        '200':
          description: 'Total Disk Space'
          schema:
            $ref: '#/definitions/TOTAL'
  '/UsedD':
    get:
      description: "Returns disk space information of the hosting server"
      produces: 
        - "application/json"
      responses:
        '200':
          description: 'Used Disk Space'
          schema:
            $ref: '#/definitions/USED'
  '/FreeD':
    get:
      description: "Returns disk space information of the hosting server"
      produces: 
        - "application/json"
      responses:
        '200':
          description: 'Free Disk Space'
          schema:
            $ref: '#/definitions/FREE'
  '/Dusage':
    get:
      description: "Returns disk space information of the hosting server"
      produces: 
        - "application/json"
      responses:
        '200':
          description: 'Usage of Disk Space'
          schema:
            $ref: '#/definitions/USAGE' 
  '/Mgmtusage':
    get:
      description: "Returns disk space information of the hosting server"
      produces: 
        - "application/json"
      responses:
        '200':
          description: 'Usage of Mgmt Space'
          schema:
            $ref: '#/definitions/MgmtUSAGE' 
  '/Diocounter':
    get:
      description: "Returns disk space information of the hosting server"
      produces: 
        - "application/json"
      responses:
        '200':
          description: 'Usage of DiskIO Space'
          schema:
            $ref: '#/definitions/DiskIO'
          
definitions:
  TOTAL:
    type: object
    required:
      - size
    properties:
        size: 
          type: string
  USED:
    type: object
    required:
      - size
    properties:
      size:
        type: string
  FREE:
    type: object
    required:
      - size
    properties:
      size:
        type: string
  USAGE:
    type: object
    required:
      - size
    properties:
      size:
        type: string       
  MgmtUSAGE:
    type: object
    required:
      - detail
      - size
    properties:
      detail:
        type: string
      size:
        type: string
  DiskIO:
    type: object
    required:
      - detail
      - size
    properties:
      detail:
        type: string
      size:
        type: string 
