# coding: utf-8

"""
    cpuinfo

    A simple service to get disk usage/space info as an example of using swagger-2.0 specification and codegen  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.diskspace import DISKSPACE  # noqa: E501
from swagger_client.rest import ApiException


class TestDISKSPACE(unittest.TestCase):
    """DISKSPACE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDISKSPACE(self):
        """Test DISKSPACE"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.diskspace.DISKSPACE()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
